### ISSUE TITLE
Add Nvim

### ISSUE THREAD

**Issue by proto-h** [njcom/morpho#12]
1. [ ] TypeScript bridge, replace Lua with TypeScript where possible.
    1. https://neovim.io/doc/user/lsp.html
    2. https://github.com/pmizio/typescript-tools.nvim
    3. https://github.com/neovim/neovim/wiki/Related-projects#api-clients
2. [ ] Web Nvim frontend, see #39 
    1. https://github.com/neovim/neovim/wiki/Related-projects#gui
    2. https://github.com/glacambre/firenvim
4. [ ] Natural language mode, see #80.
