### ISSUE TITLE
Improve PEG (including API) by writing parsers

### ISSUE THREAD

**Issue by proto-h** [njcom/morpho#15]
- [ ] Replace custom PEG Python grammar (DSL) syntax with plain PHP? Then grammar can be constructed using composition of functions. See #63 
    - [ ] Utilize PHP 8.5's feature - pipe operator (https://wiki.php.net/rfc/pipe-operator-v3). Also watch for the nice to have features in RFC: https://wiki.php.net/rfc/partial_function_application_v2, https://wiki.php.net/rfc/function-composition
    - [ ] See TypeScript as base for recursive descent parser, having tsserver, working with LSP
- [ ] Implement nice memoization with tests (Packrat), must be fast and light as possible.
- [ ] Translate to own language, see #18.
- [ ] Common AST formats
    1. JS world
        1. ESTree
        2. TypeScript AST
        3. [Unist](https://github.com/syntax-tree/unist), https://github.com/unifiedjs/unified. Used in https://github.com/jupyter-book/jupyter-book
        4. Babel AST
    2. ANTLR uses common AST for multiple input languages
    3. Tree-sitter
    4. [PSI](https://plugins.jetbrains.com/docs/intellij/psi-files.html)
- [ ] Must have composable interface and visualizations for AST and tokens
    - [ ] Mermaid
    - [ ] Graphviz
- [x] ~FASM~: doesn't make sense due complexity of FASM macros, replace with GAS
- [ ] Incremental tokenizer and parser
    1. https://lakhin.com/projects/papa-carlo/
    2. https://lady-deirdre.lakhin.com/overview.html
    3. rust-analyzer
    4. TypeScript compiler
    5. LSP
- [ ] Target languages:
    - [ ] GAS
    - [ ] C, see #74 
    - [ ] [ANTLR](https://github.com/njcom/morpho/issues/78)
    - [ ] LaTeX
    - [ ] VimScript
    - [ ] Lua
- PCRE 2 support
- Binary formats support, see https://github.com/rust-bakery/nom?tab=readme-ov-file#binary-format-parsers, Kaitai Struct and others
- UI language, see #18 
- NLP

## Notes

1. Acorn creates ESTree-compatible ASTs.
2. Esprima creates ESTree-compliant ASTs.
3. Babel parser creates Babel AST.
4. [Shift parser](https://github.com/shapesecurity/shift-parser-js) creates Shift AST.
5. TypeScript creates TypeScript AST.

## References

1. https://github.com/we-like-parsers
2. https://github.com/dstogov/llk
3. ANTLR
4. Other PEG implementations
