### ISSUE TITLE
Implement new L language

### ISSUE THREAD

**Issue by proto-h** [njcom/morpho#18]
Everything may change.

### Roadmap and requirements
 
- [x] Define starting samples in ~/module/l/
- [ ] #85
- [ ] Single executable for the target execution-environment. Choose the implementation language: Go, Lean?
- [ ] Stdlib: streams, arrows, categories, graphs, etc. Mermaid?
- [ ] Lua, VimScript for Nvim, Nginx
- [ ] Incremental parser and IDE features: TypeScript, Kotlin, Tree-sitter.
- [ ] WASM and other assemblers
- [ ] Working PEG
- [ ] MAL
- [ ] ANTLR integration
- [ ] Investigate Clojure, Racket, R, F#, OCaml, Elm, Perl, Prolog, Forth, Kotlin, Rust, Swift
- [ ] PEG in CodeMirror
- [ ] CodeMirror fork
- [ ] Investigate GraalVM, [IDEA CE](https://github.com/JetBrains/intellij-community)
- [ ] Emacs Lisp transpiler
- [ ] Light-Table
- [ ] Mathematica (Wolfram language)
- [ ] Bootstrapping, move unused to interop or archive.
- [ ] Zed and others
- [ ] Game engine, UI language
- [ ] Must be able to interop with:
    - [ ] PHP: legacy? backend
    - [ ] LLVM -> (C, C++, Rust, WASM, Haskell, Swift, Kotlin?)
    - [ ] Python: backend
    - [ ] JavaScript?: frontend
    - [ ] WASM: frontend
    - [ ] JVM, Kotlin?: for Android and iOS
    - [ ] Swift: iOS?
    - [ ] .NET?
    - [ ] Node.js?
- [ ] Must be useful for:
    - [ ] GameDev
    - [ ] Physics
    - [ ] Math
    - [ ] Org
