### ISSUE TITLE
Implement toy compiler toolchain, improve compiler

### ISSUE THREAD

**Issue by proto-h** [njcom/morpho#9]
1. [ ] ~FASM parser: preprocessor + parser, https://flatassembler.net/docs.php?article=fasmg_manual~
2. [ ] GAS
3. [ ] C
4. [ ] ELF toolchain
5. [ ] MAL: see Common Lisp, Clojure, Racket
6. [ ] C++: may be too complex, consider LLVM.

---

1. https://github.com/llvm/llvm-project/blob/339f58de16ac7a31869d189bec6cad7696958546/clang/docs/IntroductionToTheClangAST.rst
2. https://github.com/swc-project/swc
3. https://github.com/oxc-project/oxc
4. https://github.com/astral-sh/ruff/blob/main/crates/ruff_python_parser/src/lexer.rs
